apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapp-Deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 60
  template:
    metadata:
      name: springpod
      labels:
        app: spring
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:  # Added nodeSelectorTerms here
            - matchExpressions:
              - key: "node"
                operator: In
                values:
                - WorkerOne
      containers:
      - name: springappcontainer
        image: ashoknagari/spring-app-mongo:1
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /java-web-app
            port: 8080
        livenessProbe:
          httpGet:
            path: /java-web-app
            port: 8080    
        resources:
          requests:
            cpu: 200m
            memory: 250Mi
          limits:
            cpu: 500m
            memory: 500Mi  
        env:
        - name: MONGO_DB_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: springappconfigmap
              key: username
        - name: MONGO_DB_PASSWORD
          valueFrom:   
            secretKeyRef:
              name: springappsecrets
              key: password
        - name: MONGO_DB_USERNAME
          value: mongo
      nodeSelector:
        name: WorkerOne
